// react-sse/src/App.tsx
import { useState, useEffect, useRef, FunctionComponent, MutableRefObject } from 'react'
import { getTime } from './utils/getTime'
import './App.css'

const App: FunctionComponent = () => {
  const [time, setTime] = useState<string>('')
  const eventSrcRef = useRef<EventSource | null>(null);
  
  useEffect(() => {
    eventSrcRef.current = new EventSource("http://localhost:8080/event")
    eventSrcRef.current.onmessage = (e) => {
      setTime(e.data)
    }
    
    eventSrcRef.current.onerror = (e) => {
      console.log('Could not get the time:', e)
    }
    
    //clean up function
    return () => eventSrcRef.current?.close()
  }, [])
  
  return (
    <div className="App">
      <h1>Server-Sent Events</h1>
      <button onClick={getTime}>Get Time</button>
      <h2>{time}</h2>
      
    </div>
  )
}

export default App

// svelte-sse/src/App.svelte
<script>
  import { onMount } from "svelte";
  let time = "";
  
  onMount (() => {
    const eventSrc = new EventSource("http://localhost:8080/event");
    eventSrc.onmessage = function (event) {
      time = event.data;
    }
    
    eventSrc.onerror = function (event) {
      console.log(event);
    }
  })
  
  async function getTime() {
    const res = await fetch("http://localhost:8080/time");
    if (res.status !== 200) {
      console.log("could not connect to server")
    }
    return res;
  } 
  
</script>

<main>
  
  <h1>Server-Sent Events</h1>
  <p>Time : { time }</p>
  <button on:click="{getTime}">Get Time</button>
</main>

<style>
  
</style>
